#!/bin/bash

#SBATCH --job-name=Hybpiper_array
#SBATCH --partition=normal
#SBATCH --mem-per-cpu=20G
#SBATCH --cpus-per-task=8
#SBATCH --account=Coryphoideae
#              D-HH:MM:SS This is the max running time allowed on GDK
#SBATCH --time=0-04:00:00
#SBATCH --array 0-138%70

#This line should enable the activation of specific conda environments
source /home/owrisberg/miniconda3/etc/profile.d/conda.sh

#Activating conda base environment 
conda activate base

#Going to folder with data
cd /home/owrisberg/Coryphoideae/work_flow/03_hybpiper

#List of input files
inputfiles=($(cat ./namelist_array.txt))

#Program to run in array:
/home/owrisberg/Coryphoideae/github_code/HybPiper/reads_first.py --cpu 10 --readfiles ../02_trimmed/"${inputfiles[$SLURM_ARRAY_TASK_ID]}"_1P.fastq ../02_trimmed/"${inputfiles[$SLURM_ARRAY_TASK_ID]}"_2P.fastq --unpaired ../02_trimmed/"${inputfiles[$SLURM_ARRAY_TASK_ID]}"_UN.fastq -b /home/owrisberg/Coryphoideae/target_sequence/PhyloPalms_loci_renamed_794-176_HEYcorrected.fasta --prefix ${inputfiles[$SLURM_ARRAY_TASK_ID]} --bwa

